[package]
name = "rrbc-asm"
version = "0.1.0"
edition = "2024"

[dependencies]
rrbc-tacky = { path = "../tacky/", optional = true }
rrbc-semantic-analysis = { path = "../semantic-analysis/" }

[features]
default = ["tacky"]
tacky = ["dep:rrbc-tacky"]
